### ISSUE TITLE
Error running matchpyramid

### ISSUE THREAD

**Issue by shizhouxing** [NTMC-Community/MatchZoo#633]
### Describe the bug

When I ran the tutorial code https://github.com/NTMC-Community/MatchZoo/blob/master/tutorials/wikiqa/matchpyramid.ipynb, I got the following error:

```
2019-02-23 22:51:08.473125: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Epoch 1/20
 51/102 [==============>...............] - ETA: 6s - loss: 4.7849Traceback (most recent call last):
  File "msrp.py", line 150, in <module>
    history = model.fit_generator(train_generator, epochs=20, callbacks=[evaluate], workers=30, use_multiprocessing=True)
  File "/home/shixingzhou/softwares/Python-3.6.4rc1/env/lib/python3.6/site-packages/matchzoo/engine/base_model.py", line 265, in fit_generator
    verbose=verbose, **kwargs
  File "/home/shixingzhou/softwares/Python-3.6.4rc1/env/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/shixingzhou/softwares/Python-3.6.4rc1/env/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/shixingzhou/softwares/Python-3.6.4rc1/env/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/shixingzhou/softwares/Python-3.6.4rc1/env/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/shixingzhou/softwares/Python-3.6.4rc1/env/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/shixingzhou/softwares/Python-3.6.4rc1/env/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/shixingzhou/softwares/Python-3.6.4rc1/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1399, in __call__
    run_metadata_ptr)
  File "/home/shixingzhou/softwares/Python-3.6.4rc1/env/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [8,1] vs. shape[1] = [7,1]
         [[{{node loss/dense_1_loss/concat_1}} = ConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](loss/dense_1_loss/lambda_2/strid
ed_slice, loss/dense_1_loss/lambda_4/strided_slice, loss/dense_1_loss/lambda_6/strided_slice, loss/dense_1_loss/lambda_8/strided_slice, loss/dense_1_loss/lambda_10/strided_slice,
 training/Adam/gradients/loss/dense_1_loss/Mean_3_grad/Maximum)]]
```

And I have modified `model.params['embedding_input_dim'] = preprocessor.context['vocab_size']` into `model.params['embedding_input_dim'] = preprocessor.context['vocab_size'] + 1`. Otherwise, error happens at `model.load_embedding_matrix(embedding_matrix)`.

### To Reproduce
Just `https://github.com/NTMC-Community/MatchZoo/blob/master/tutorials/wikiqa/matchpyramid.ipynb`

### Context
 - **OS** [e.g. Windows 10, macOS 10.14]: Ubuntu 14.04
 - **Hardware** [e.g. CPU only, GTX 1080 Ti]: CPU

MatchZoo version is 2.0

**Comment by uduse** [comment]
A duplicate of #601 

@faneshion @bwanglzu We should update our tutorials ASAP.

**Comment by uduse** [comment]
A duplicate of #615 ?

**Comment by shizhouxing** [comment]
Has the issue been fixed? I reinstalled the latest MatchZoo from github and it appears that the issue still exists.

**Comment by uduse** [comment]
@shizhouxing I believe it's fixed in branch 2.1-dev, but not released to the master branch yet.

**Comment by shizhouxing** [comment]
As for branch 2.1-dev, it seems that error has been fixed. But I then met the following error:
```
Traceback (most recent call last):
  File "msrp.py", line 133, in <module>
    train_generator = mz.DPoolPairDataGenerator(train_pack_processed,
AttributeError: module 'matchzoo' has no attribute 'DPoolPairDataGenerator'
```

**Comment by shizhouxing** [comment]
@uduse It seems that the issue still exists in branch 2.1-dev.

**Comment by uduse** [comment]
@shizhouxing Ok, we will update the tutorials ASAP. Stay tuned.

**Comment by shizhouxing** [comment]
@uduse Thank you

**Comment by bwanglzu** [comment]
@uduse @faneshion create an issue for tutorials?

**Comment by pl8787** [comment]
@shizhouxing I can not reproduce this running error, in my environment, it is running well.
How about check your MatchZoo version? Please uninstall then install the newest one.

**Comment by MathildaSu** [comment]
Hi, I ran into the same issue. I just installed the newest version. and 
```preprocessor = mz.preprocessors.DSSMPreprocessor()
preprocessor.fit(train_pack)

train_processed = preprocessor.transform(train_pack)
valid_processed = preprocessor.transform(valid_pack)
predict_processed = preprocessor.transform(predict_pack)


ranking_task = mz.tasks.Ranking(loss=mz.losses.RankCrossEntropyLoss(num_neg=4))
ranking_task.metrics = [
    mz.metrics.NormalizedDiscountedCumulativeGain(k=3),
    mz.metrics.NormalizedDiscountedCumulativeGain(k=5),
    mz.metrics.MeanAveragePrecision()
]

model = mz.models.DenseBaseline()
model.params['input_shapes'] = preprocessor.context['input_shapes']
model.params['task'] = ranking_task
model.params['mlp_num_layers'] = 2
model.params['mlp_num_units'] = 300
model.params['mlp_num_fan_out'] = 128
model.params['mlp_activation_func'] = 'relu'
model.guess_and_fill_missing_params(verbose=0)
model.build()
model.compile()
model.backend.summary()

train_generator = mz.DataGenerator(train_processed, batch_size=64, shuffle=True)
valid_x, valid_y = valid_processed.unpack()
pred_x, pred_y = predict_processed.unpack()
evaluate = mz.callbacks.EvaluateAllMetrics(model, x=valid_x, y=valid_y, batch_size=256)
history = model.fit_generator(train_generator, epochs=20, callbacks=[evaluate], workers=5, use_multiprocessing=False)
```

Got following errors:
```
Epoch 1/20
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1326     try:
-> 1327       return fn(*args)
   1328     except errors.OpError as e:

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1311       return self._call_tf_sessionrun(
-> 1312           options, feed_dict, fetch_list, target_list, run_metadata)
   1313 

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1419             self._session, options, feed_dict, fetch_list, target_list,
-> 1420             status, run_metadata)
   1421 

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    515             compat.as_text(c_api.TF_Message(self.status.status)),
--> 516             c_api.TF_GetCode(self.status.status))
    517     # Delete the underlying status object from memory otherwise it stays alive

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [13,1] vs. shape[4] = [12,1]
	 [[Node: loss_1/dense_8_loss/concat_1 = ConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](loss_1/dense_8_loss/lambda_12/strided_slice, loss_1/dense_8_loss/lambda_14/strided_slice, loss_1/dense_8_loss/lambda_16/strided_slice, loss_1/dense_8_loss/lambda_18/strided_slice, loss_1/dense_8_loss/lambda_20/strided_slice, loss_1/dense_8_loss/concat_1/axis)]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-11-3f836120c893> in <module>
      3 pred_x, pred_y = predict_processed.unpack()
      4 evaluate = mz.callbacks.EvaluateAllMetrics(model, x=valid_x, y=valid_y, batch_size=256)
----> 5 history = model.fit_generator(train_generator, epochs=20, callbacks=[evaluate], workers=5, use_multiprocessing=False)
      6 
      7 

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/matchzoo/engine/base_model.py in fit_generator(self, generator, epochs, verbose, **kwargs)
    274             generator=generator,
    275             epochs=epochs,
--> 276             verbose=verbose, **kwargs
    277         )
    278 

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1416             use_multiprocessing=use_multiprocessing,
   1417             shuffle=shuffle,
-> 1418             initial_epoch=initial_epoch)
   1419 
   1420     @interfaces.legacy_generator_methods_support

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    215                 outs = model.train_on_batch(x, y,
    216                                             sample_weight=sample_weight,
--> 217                                             class_weight=class_weight)
    218 
    219                 outs = to_list(outs)

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight)
   1215             ins = x + y + sample_weights
   1216         self._make_train_function()
-> 1217         outputs = self.train_function(ins)
   1218         return unpack_singleton(outputs)
   1219 

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
   2719                     'In order to feed symbolic tensors to a Keras model '
   2720                     'in TensorFlow, you need tensorflow 1.8 or higher.')
-> 2721             return self._legacy_call(inputs)
   2722 
   2723 

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _legacy_call(self, inputs)
   2691         session = get_session()
   2692         updated = session.run(fetches=fetches, feed_dict=feed_dict,
-> 2693                               **self.session_kwargs)
   2694         return updated[:len(self.outputs)]
   2695 

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    903     try:
    904       result = self._run(None, fetches, feed_dict, options_ptr,
--> 905                          run_metadata_ptr)
    906       if run_metadata:
    907         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1138     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1139       results = self._do_run(handle, final_targets, final_fetches,
-> 1140                              feed_dict_tensor, options, run_metadata)
   1141     else:
   1142       results = []

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1319     if handle is None:
   1320       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1321                            run_metadata)
   1322     else:
   1323       return self._do_call(_prun_fn, handle, feeds, fetches)

~/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1338         except KeyError:
   1339           pass
-> 1340       raise type(e)(node_def, op, message)
   1341 
   1342   def _extend_graph(self):

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [13,1] vs. shape[4] = [12,1]
	 [[Node: loss_1/dense_8_loss/concat_1 = ConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](loss_1/dense_8_loss/lambda_12/strided_slice, loss_1/dense_8_loss/lambda_14/strided_slice, loss_1/dense_8_loss/lambda_16/strided_slice, loss_1/dense_8_loss/lambda_18/strided_slice, loss_1/dense_8_loss/lambda_20/strided_slice, loss_1/dense_8_loss/concat_1/axis)]]

Caused by op 'loss_1/dense_8_loss/concat_1', defined at:
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/asyncio/base_events.py", line 1451, in _run_once
    handle._run()
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-ab326020b8ef>", line 10, in <module>
    model.compile()
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/matchzoo/engine/base_model.py", line 220, in compile
    loss=self._params['task'].loss)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/keras/engine/training.py", line 342, in compile
    sample_weight, mask)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/keras/engine/training_utils.py", line 404, in weighted
    score_array = fn(y_true, y_pred)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/matchzoo/losses/rank_cross_entropy_loss.py", line 50, in __call__
    labels = K.concatenate(labels, axis=-1)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1956, in concatenate
    return tf.concat([to_dense(x) for x in tensors], axis)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1181, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 949, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/users/grad/ting/tr.ting/anaconda3/envs/keras_cpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [13,1] vs. shape[4] = [12,1]
	 [[Node: loss_1/dense_8_loss/concat_1 = ConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](loss_1/dense_8_loss/lambda_12/strided_slice, loss_1/dense_8_loss/lambda_14/strided_slice, loss_1/dense_8_loss/lambda_16/strided_slice, loss_1/dense_8_loss/lambda_18/strided_slice, loss_1/dense_8_loss/lambda_20/strided_slice, loss_1/dense_8_loss/concat_1/axis)]]
```
system: Ubuntu 
Hardware: CPU only
MAtchzoo version: 2.1.0

**Comment by MathildaSu** [comment]
NVM I figured out. Because `losses = RankCrossEntropyLoss` needs pair-wise data.
